### ISSUE TITLE
Duplicate reply packets when pinging multiple targets

### ISSUE THREAD

**Issue by Giux3** [schweikert/fping#277] opened 2023-08-02 13:23 UTC
Masking first 2 octets (A.B) 

**on v 4.0** was ok

A.B.116.146 is alive
A.B.142.68 is alive
A.B.108.7 is alive
A.B.155.155 is alive
A.B.141.100 is alive
A.B.144.164 is alive
A.B.156.69 is alive
A.B.109.230 is alive
A.B.140.88 is alive
A.B.156.167 is alive
A.B.144.81 is alive
A.B.143.98 is alive
A.B.143.173 is unreachable

**on v 5.1:**

A.B.116.146 is alive
A.B.142.68 is alive
A.B.156.167 is alive
A.B.108.7 is alive
A.B.144.164 is alive
A.B.144.164 : duplicate for [0], 64 bytes, 65.4 ms
A.B.141.100 is alive
A.B.141.100 : duplicate for [0], 64 bytes, 116 ms
A.B.155.155 is alive
A.B.155.155 : duplicate for [0], 64 bytes, 45.4 ms
A.B.156.69 is alive
A.B.156.69 : duplicate for [0], 64 bytes, 197 ms
A.B.109.230 is alive
A.B.140.88 is alive
A.B.109.230 : duplicate for [0], 64 bytes, 144 ms
A.B.140.88 : duplicate for [0], 64 bytes, 138 ms
A.B.144.81 is alive
A.B.143.98 is unreachable
A.B.143.173 is unreachable

test was done behind same switch on two different machines 
( mint 19.3 fping/bionic,now 4.0-6 amd64  VS ubuntu 22.04 lts fping/jammy,now 5.1-1 amd64)

**Comment by Giux3** [comment] 2023-09-22 10:38
sorry for pinging , hoping for a reply...

is this expected and normal behaviour on slow links?

**Comment by sky00747** [comment] 2024-04-03 07:17
i what why ? [1], timed out (NaN avg, 100% loss)

**Comment by auerswal** [comment] 2024-04-14 13:25
I do not see this problem when pinging multiple targets. I would assume that `fping` reports actual duplicate packets, i.e., I would expect `fping` to work correctly. I would expect that a packet capture (using, e.g., `tcpdump`) would show these duplicate reply packets.

Since the reports about duplicate reply packets are sent to standard error while the normal output (`alive` and `unreachable`) goes to standard output, you might be able to ignore the reports of duplicates by redirecting standard error:

```
fping ... 2>/dev/null
```

**Comment by Giux3** [comment] 2024-04-15 06:52
that can be fine despite the redirection of other useful messages with the solution provided
however there is something different in the behaviour of v. 4 vs 5.1 maybe more evident over slower networks

If the behaviour is expected is ok but confirmation is welcome

**Comment by schweikert** [comment] 2024-04-20 07:00
Showing duplicates is expected behavior and I assume that this is working correctly (I don't know why there is a difference with 4.0, which is quite old). If it is wrong, can you verify with tcpdump or similar that you are not getting duplicate responses? I will close this for now.

**Closed by schweikert** 2024-04-20 07:00 UTC
