### ISSUE TITLE
The minimum values in -Q summaries are always 0

### ISSUE THREAD

**Issue by jafaber** [schweikert/fping#74] opened 2015-02-11 16:34 UTC
I use a script to pipe the output of fping (almost) straight into rrdtool. This works great, except that the min value is always 0.

```sh
cat hosts | fping -A -u -l -p200 -Q1
[17:26:59]
172.31.128.1  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/9.59/13.7
192.168.101.1 : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/1.10/1.24
192.168.1.44  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/0.17/0.20
[17:27:00]
172.31.128.1  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/9.62/12.4
192.168.101.1 : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/1.03/1.11
192.168.1.44  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/0.17/0.19
[17:27:01]
172.31.128.1  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/9.47/11.8
192.168.101.1 : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/1.05/1.09
192.168.1.44  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.00/0.20/0.24
```

The alternative way is to let fping quit every second and use that summary, which does include the correct minimum:

```sh
cat ../etc/pinger.hosts | fping -A -u -p200 -c5
172.31.128.1  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 11.6/14.4/17.0
192.168.101.1 : xmt/rcv/%loss = 5/5/0%, min/avg/max = 1.09/1.17/1.40
192.168.1.44  : xmt/rcv/%loss = 5/5/0%, min/avg/max = 0.17/1.19/5.20
```

The first solution seems much nicer to me: not starting new processes every second and letting fping handle all the timing related issues.

**Comment by PawelDefee** [comment] 2015-05-18 11:55
Rather strange - could this be a compiler issue (bug) ? I cannot reproduce this problem. Also, looking at fping.c, all the variables for the minimum value calculation are initialized and set correctly..

**Comment by jafaber** [comment] 2015-05-18 13:40
Thank you for looking into this.

I have several older different Linux distributions that run old versions of fping and show this 0 minimum quirk. The latest fping version I could find that doesn't work was 3.0.

However, I just tried again on my fully updated Fedora 21 (fping 3.1) and there it seems to work fine. So whatever it was, it seems to have been fixed.

The way I just tested it again on different systems:

echo -e "8.8.8.8\n8.8.4.4" | fping -A -u -l -p200 -Q1

Thank you!

**Comment by PawelDefee** [comment] 2015-05-18 14:20
Right, I was testing the latest (3.10). But indeed it looks like there was a bug in 3.0 that was fixed in some subsequent release:

3.0 version setting of minimum ping:
`if( this_reply < h->min_reply_i ) h->min_reply_i = this_reply;`

was changed to this in some later revision:
`if( !h->min_reply_i || this_reply < h->min_reply_i ) h->min_reply_i = this_reply;`

So that fixes it :)

**Comment by jafaber** [comment] 2015-05-18 14:28
Cool. Classical bug :)

Thank you for following up on this. Good to know that it's fixed now, this
should make my rrdtool script that much easier and more efficient.

--
Jannes

**Comment by schweikert** [comment] 2015-05-18 15:01
Thank you for the analysis. I close the issue then.

**Closed by schweikert** 2015-05-18 15:01 UTC
Labels: bug
